In [16]:
#-----Task-1-----
#Store the given sensor readings using appropriate Python data structures, then perform the following tasks.
#1.Store and display the sensor readings.
data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

for row in data:
    print(row)
print("\n")

#2.dentify high temperature.
for row in data:
    temperature = row[1]

    if temperature > 40:
        print(row[0], "h: High Temperature Alert")
    else:
        print(row[0], "h: Temperature Normal")
print("\n")

#3.Identify low battery.
for row in data:
  charge = row[4]

  if charge < 50:
      print(row[0], "h: Low Battery Alert")
  else:
      print(row[0], "h: Battery Charge Normal")
print("\n")

#4.Create a function.
def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"

for row in data:
    print(row[0], "h:", battery_status(row[4]))
print("\n")

#-----Task-2-----
#Analysis Using NumPy
import numpy as np

D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

#1.Find the shape of the array
print("Shape:", D.shape)
print("\n")

#2.Calculate the average of each parameter
print("Average Temperature:", np.mean(D[:, 0]))
print("Average Voltage:", np.mean(D[:, 1]))
print("Average Current:", np.mean(D[:, 2]))
print("Average Charge:", np.mean(D[:, 3]))
print("\n")

#3.Find the maximum and minimum temperature
print("Maximum Temperature:", np.max(D[:, 0]))
print("Minimum Temperature:", np.min(D[:, 0]))
print("\n")

#4.Extract the voltage column
print("Voltage Column:")
print(D[:, 1])
print("\n")

#5.Identify high-temperature readings
print("High Temperature Readings:")
print(D[D[:, 0] > 40])
print("\n")

#6.Identify low battery readings
print("Low Battery Readings:")
print(D[D[:, 3] < 50])
print("\n")

#-----Task-3-----
#Analysis Using Linear Algebra
#1.Transpose
import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

Y = A @ X

print("Y =")
print(Y)
print("Transpose:")
print(A.T)
print("\n")

#2.Determinant
print("Determinant:", np.linalg.det(A))
print("\n")

#3.Inverse
print("Inverse:")
print(np.linalg.inv(A))
print("\n")

#Solving a System of Equations
A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([100, 120])

solution = np.linalg.solve(A, B)
print("Solution:")
print("x =", solution[0])
print("y =", solution[1])
print("\n")

#-----Task-4-----
#1.Find the rate of change of battery charge
print("dC/dt = -2 - t")
#Calculate the discharge rate
rate_2 = -2 - 2
rate_5 = -2 - 5
#3.Interpret the result
print("Discharge rate at t=2:", rate_2, "%/hour")
print("Discharge rate at t=5:", rate_5, "%/hour")
print("\n")

#----Final Analysis----
print("First high temperature: 4 hours")
print("Total charge loss:", 95 - 48, "%")
print("Final Decision: MONITOR")

[0, 32, 400, 20, 95]
[1, 35, 395, 22, 88]
[2, 38, 390, 25, 80]
[3, 40, 385, 28, 70]
[4, 42, 380, 30, 60]
[5, 45, 375, 32, 48]


0 h: Temperature Normal
1 h: Temperature Normal
2 h: Temperature Normal
3 h: Temperature Normal
4 h: High Temperature Alert
5 h: High Temperature Alert


0 h: Battery Charge Normal
1 h: Battery Charge Normal
2 h: Battery Charge Normal
3 h: Battery Charge Normal
4 h: Battery Charge Normal
5 h: Low Battery Alert


0 h: High
1 h: High
2 h: High
3 h: Medium
4 h: Medium
5 h: Low


Shape: (6, 4)


Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5


Maximum Temperature: 45
Minimum Temperature: 32


Voltage Column:
[400 395 390 385 380 375]


High Temperature Readings:
[[ 42 380  30  60]
 [ 45 375  32  48]]


Low Battery Readings:
[[ 45 375  32  48]]


Y =
[[105]
 [115]]
Transpose:
[[2 1]
 [1 3]]


Determinant: 5.000000000000001


Inverse:
[[ 0.6 -0.2]
 [-0.2  0.4]]


Solution:
x = 36.0
y = 28.0


d